version: "3.8"

services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin123
    volumes:
      - couchdb_data:/opt/couchdb/data

  aerospike:
    image: aerospike/aerospike-server:7.1.0.4
    container_name: aerospike
    restart: always
    ports:
      - "3000:3000"   # service
      - "3001:3001"   # management
      - "3002:3002"   # fabric (cluster)
      - "3003:3003"   # info
    volumes:
      - aerospike_data:/opt/aerospike/data
    command: >
      --config-file /etc/aerospike/aerospike.conf

volumes:
  couchdb_data:
  aerospike_data: